---
- name: Install MySQL Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "mysql-utilities"
  - "mytop"
  - "mycli"
  when: sql_mysql_tools_install and (ansible_distribution == "Fedora")

- name: Install MySQL Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "mysql-client"
  - "mysql-workbench"
  when: sql_mysql_tools_install and (ansible_distribution == "Ubuntu")

- name: Install PostreSQL Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "pgadmin3"
  - "pgmodeler"
  - "pgcenter"
  - "pgtoolkit"
  - "pg_top"
  - "pg_view"
  - "postgresql"
  when: sql_postgresql_tools_install and (ansible_distribution == "Fedora")

- name: Install PostreSQL Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "pgadmin3"
  - "pgcli"
  - "pgmodeler"
  - "postgresql-client"
  when: sql_postgresql_tools_install and (ansible_distribution == "Ubuntu")

- name: Download DataGrip Tarball
  become: no
  get_url:
      url: "https://download.jetbrains.com/datagrip/datagrip-{{sql_datagrip_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/datagrip-{{sql_datagrip_version}}.tar.gz"
      mode: 0444
  when: sql_datagrip_install

- name: Uncompress DataGrip Tarball
  become: no
  unarchive:
      src: "{{ansible_user_dir}}/{{base_download_directory}}/datagrip-{{sql_datagrip_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{ansible_user_dir}}/{{base_software_directory}}/DataGrip-{{sql_datagrip_version}}/build.txt"
  when: sql_datagrip_install

- name: Create Softlink To DataGrip
  become: no
  file:
      src: "{{ansible_user_dir}}/{{base_software_directory}}/DataGrip-{{sql_datagrip_version}}"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}/datagrip"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: sql_datagrip_install

- name: Create Desktop Icon For DataGrip
  become: no
  template:
      src: "templates/datagrip.desktop.j2"
      dest: "{{ansible_user_dir}}/Desktop/datagrip.desktop"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0755
  when: sql_datagrip_install

- name: Set Global Environment To Have DataGrip Use Shared JDK
  become: yes
  template:
      src: "templates/datagrip-environment.sh.j2"
      dest: "/etc/profile.d/datagrip-environment.sh"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
  when: sql_datagrip_share_jdk

- name: Remove DataGrip's Embedded JDK
  become: no
  file:
      path: "{{ansible_user_dir}}/{{base_software_directory}}/datagrip/jre"
      state: absent
  when: sql_datagrip_share_jdk

